# Copyright 2019 IBM Corporation All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

dist: xenial
language: python
python: 3.8.7

addons:
  sonarcloud:
      organisation: "qradar-app-framework"

script:
  - python -m pip install --upgrade pip
  - python -m pip list
  - ./lint.sh && ./test.sh
    # sonar scan skipped if build was triggered by create pull request or create tag or fork build.
    # this will only run once merged into the qpylib repository - not on forks/pull requests
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "IBM/qpylib" ]; then
      sonar-scanner;
    fi

after_success:
  - if [[ $TRAVIS_TAG ]]; then
      ./build.sh ${TRAVIS_TAG};
    else
      ./build.sh "0.0.dev${TRAVIS_BUILD_NUMBER}";
    fi

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file:
    - dist/qpylib-${TRAVIS_TAG}.tar.gz
    - dist/qpylib-${TRAVIS_TAG}-py3-none-any.whl
  skip_cleanup: true
  on:
    tags: true
